/* ============================================================
   DATOS DE EJEMPLO — simulan la exportación a Excel de
   Microsoft Forms (mismas columnas). Nombres ficticios.
   Máximo 3 solicitudes por cada TRAMO de 30 min.
   ============================================================ */

const DATOS_EJEMPLO = [
  // Lunes: Tramo 16:00-16:30 (3), Tramo 16:30-17:00 (3), Tramo 17:00-17:30 (3), etc.
  { 'Id': 1, 'Hora de inicio': '2025-09-02 09:12', 'Correo electrónico': 'familia01@example.com',
    'Nombre y apellidos del alumno/a': 'Lucía Herrera Campos', 'Curso': '6º Enseñanzas Profesionales',
    'Especialidad': 'Piano', 'Edad': '17', 'Teléfono': '600000001', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '16:00-16:30', 'Martes': '', 'Miércoles': '18:00-18:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 2, 'Hora de inicio': '2025-09-02 09:30', 'Correo electrónico': 'familia02@example.com',
    'Nombre y apellidos del alumno/a': 'Mario Quintana Ríos', 'Curso': '5º Enseñanzas Profesionales',
    'Especialidad': 'Percusión', 'Edad': '17', 'Teléfono': '600000002', 'Profesor/a tutor/a': 'J. Peña',
    'Localidad de residencia': 'Miguelturra', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'Sí',
    'Lunes': '16:00-16:30', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 3, 'Hora de inicio': '2025-09-02 10:05', 'Correo electrónico': 'familia03@example.com',
    'Nombre y apellidos del alumno/a': 'Carla Estévez Mena', 'Curso': '6EP', 'Especialidad': 'Piano',
    'Edad': '18', 'Teléfono': '600000003', 'Profesor/a tutor/a': 'M. Ortega', 'Localidad de residencia': 'Daimiel',
    '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '16:00-16:30', 'Martes': '16:30-17:00', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 4, 'Hora de inicio': '2025-09-02 10:20', 'Correo electrónico': 'familia04@example.com',
    'Nombre y apellidos del alumno/a': 'Olivia Manrique Deza', 'Curso': '6º Enseñanzas Profesionales',
    'Especialidad': 'Piano', 'Edad': '17', 'Teléfono': '600000023', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '16:30-17:00', 'Martes': '', 'Miércoles': '16:00-16:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 5, 'Hora de inicio': '2025-09-02 10:45', 'Correo electrónico': 'familia05@example.com',
    'Nombre y apellidos del alumno/a': 'Valentina Roldán Haya', 'Curso': '5º Enseñanzas Profesionales',
    'Especialidad': 'Viola', 'Edad': '16', 'Teléfono': '600000029', 'Profesor/a tutor/a': 'P. Núñez',
    'Localidad de residencia': 'Puertollano', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '16:30-17:00', 'Martes': '', 'Miércoles': '', 'Jueves': '16:00-16:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 6, 'Hora de inicio': '2025-09-02 11:02', 'Correo electrónico': 'familia06@example.com',
    'Nombre y apellidos del alumno/a': 'Aitana Bermejo Luz', 'Curso': '4º Enseñanzas Profesionales',
    'Especialidad': 'Percusión', 'Edad': '16', 'Teléfono': '600000005', 'Profesor/a tutor/a': 'J. Peña',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '17:00-17:30', 'Martes': '', 'Miércoles': '19:00-19:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 7, 'Hora de inicio': '2025-09-02 11:30', 'Correo electrónico': 'familia07@example.com',
    'Nombre y apellidos del alumno/a': 'Marc Ivars Bono', 'Curso': '6º Enseñanzas Profesionales',
    'Especialidad': 'Saxofón', 'Edad': '18', 'Teléfono': '600000018', 'Profesor/a tutor/a': 'C. Salas',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '17:00-17:30', 'Martes': '', 'Miércoles': '', 'Jueves': '19:00-19:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 8, 'Hora de inicio': '2025-09-02 12:00', 'Correo electrónico': 'familia08@example.com',
    'Nombre y apellidos del alumno/a': 'Hugo Lafuente Soria', 'Curso': '6º Enseñanzas Profesionales',
    'Especialidad': 'Trombón', 'Edad': '18', 'Teléfono': '600000004', 'Profesor/a tutor/a': 'A. Redondo',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '17:00-17:30', 'Martes': '', 'Miércoles': '18:00-18:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 9, 'Hora de inicio': '2025-09-02 12:14', 'Correo electrónico': 'familia09@example.com',
    'Nombre y apellidos del alumno/a': 'Irene Castaño Bel', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Clarinete', 'Edad': '13', 'Teléfono': '600000009', 'Profesor/a tutor/a': 'R. Cañas',
    'Localidad de residencia': 'Malagón', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '18:00-18:30', 'Miércoles': '', 'Jueves': '', 'Viernes': '17:00-17:30', 'Observaciones': '' },
  { 'Id': 10, 'Hora de inicio': '2025-09-02 12:40', 'Correo electrónico': 'familia10@example.com',
    'Nombre y apellidos del alumno/a': 'Bruno Antón Mora', 'Curso': '4º Enseñanzas Elementales',
    'Especialidad': 'Fagot', 'Edad': '11', 'Teléfono': '600000010', 'Profesor/a tutor/a': 'R. Cañas',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'Sí',
    'Lunes': '18:00-18:30', 'Martes': '', 'Miércoles': '17:00-17:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 11, 'Hora de inicio': '2025-09-02 13:05', 'Correo electrónico': 'familia11@example.com',
    'Nombre y apellidos del alumno/a': 'Daniela Roca Insa', 'Curso': '2º Enseñanzas Elementales',
    'Especialidad': 'Contrabajo', 'Edad': '9', 'Teléfono': '600000011', 'Profesor/a tutor/a': 'P. Núñez',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '18:00-18:30', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 12, 'Hora de inicio': '2025-09-02 13:22', 'Correo electrónico': 'familia12@example.com',
    'Nombre y apellidos del alumno/a': 'Álvaro Pinto Vidal', 'Curso': '4º Enseñanzas Profesionales',
    'Especialidad': 'Flauta', 'Edad': '16', 'Teléfono': '600000012', 'Profesor/a tutor/a': 'C. Salas',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'Sí',
    'Lunes': '18:00-18:30', 'Martes': '17:00-17:30', 'Miércoles': '18:00-18:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 13, 'Hora de inicio': '2025-09-02 13:47', 'Correo electrónico': 'familia13@example.com',
    'Nombre y apellidos del alumno/a': 'Claudia Beltrán Haro', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Piano', 'Edad': '13', 'Teléfono': '600000013', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Malagón', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '19:00-19:30', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 14, 'Hora de inicio': '2025-09-02 14:10', 'Correo electrónico': 'familia14@example.com',
    'Nombre y apellidos del alumno/a': 'Rodrigo Peral Onteniente', 'Curso': '5º Enseñanzas Profesionales',
    'Especialidad': 'Percusión', 'Edad': '17', 'Teléfono': '600000014', 'Profesor/a tutor/a': 'J. Peña',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '19:00-19:30', 'Martes': '', 'Miércoles': '19:00-19:30', 'Jueves': '17:00-17:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 15, 'Hora de inicio': '2025-09-02 14:35', 'Correo electrónico': 'familia15@example.com',
    'Nombre y apellidos del alumno/a': 'Jimena Cruz Alcolea', 'Curso': '3º Enseñanzas Profesionales',
    'Especialidad': 'Violín', 'Edad': '15', 'Teléfono': '600000015', 'Profesor/a tutor/a': 'P. Núñez',
    'Localidad de residencia': 'Torralba de Calatrava', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '19:00-19:30', 'Martes': '', 'Miércoles': '', 'Jueves': '16:00-16:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 16, 'Hora de inicio': '2025-09-02 15:00', 'Correo electrónico': 'familia16@example.com',
    'Nombre y apellidos del alumno/a': 'Teo Lozano Gala', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Trompa', 'Edad': '12', 'Teléfono': '600000016', 'Profesor/a tutor/a': 'A. Redondo',
    'Localidad de residencia': 'Manzanares', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '17:00-17:30', 'Miércoles': '', 'Jueves': '16:00-16:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 17, 'Hora de inicio': '2025-09-02 15:21', 'Correo electrónico': 'familia17@example.com',
    'Nombre y apellidos del alumno/a': 'Alma Ballesteros Coto', 'Curso': '2º Enseñanzas Profesionales',
    'Especialidad': 'Oboe', 'Edad': '14', 'Teléfono': '600000017', 'Profesor/a tutor/a': 'R. Cañas',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '19:00-19:30', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 18, 'Hora de inicio': '2025-09-02 16:02', 'Correo electrónico': 'familia18@example.com',
    'Nombre y apellidos del alumno/a': 'Noa Ferrando Prats', 'Curso': '4º Enseñanzas Elementales',
    'Especialidad': 'Piano', 'Edad': '11', 'Teléfono': '600000019', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '17:00-17:30', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 19, 'Hora de inicio': '2025-09-02 16:30', 'Correo electrónico': 'familia19@example.com',
    'Nombre y apellidos del alumno/a': 'Iker Salvatierra Pons', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Percusión', 'Edad': '13', 'Teléfono': '600000020', 'Profesor/a tutor/a': 'J. Peña',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '19:00-19:30', 'Miércoles': '', 'Jueves': '', 'Viernes': '20:00-20:30', 'Observaciones': '' },
  { 'Id': 20, 'Hora de inicio': '2025-09-02 17:15', 'Correo electrónico': 'familia20@example.com',
    'Nombre y apellidos del alumno/a': 'Candela Osorio Real', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Violín', 'Edad': '12', 'Teléfono': '600000021', 'Profesor/a tutor/a': 'P. Núñez',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '18:00-18:30', 'Jueves': '16:00-16:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 21, 'Hora de inicio': '2025-09-03 09:05', 'Correo electrónico': 'familia22@example.com',
    'Nombre y apellidos del alumno/a': 'Pau Requena Sanchís', 'Curso': '2º Enseñanzas Profesionales',
    'Especialidad': 'Trompeta', 'Edad': '14', 'Teléfono': '600000022', 'Profesor/a tutor/a': 'A. Redondo',
    'Localidad de residencia': 'Almagro', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '18:00-18:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 22, 'Hora de inicio': '2025-09-03 09:40', 'Correo electrónico': 'familia24@example.com',
    'Nombre y apellidos del alumno/a': 'Leo Cifuentes Vara', 'Curso': '3º Enseñanzas Elementales',
    'Especialidad': 'Violonchelo', 'Edad': '10', 'Teléfono': '600000024', 'Profesor/a tutor/a': 'P. Núñez',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '18:00-18:30', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 23, 'Hora de inicio': '2025-09-03 10:12', 'Correo electrónico': 'familia25@example.com',
    'Nombre y apellidos del alumno/a': 'Martina Espada Coll', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Piano', 'Edad': '13', 'Teléfono': '600000025', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Malagón', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 24, 'Hora de inicio': '2025-09-03 10:55', 'Correo electrónico': 'familia26@example.com',
    'Nombre y apellidos del alumno/a': 'Gael Montoro Isla', 'Curso': '2º Enseñanzas Profesionales',
    'Especialidad': 'Trombón', 'Edad': '14', 'Teléfono': '600000026', 'Profesor/a tutor/a': 'A. Redondo',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'Sí',
    'Lunes': '', 'Martes': '16:30-17:00', 'Miércoles': '', 'Jueves': '16:30-17:00', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 25, 'Hora de inicio': '2025-09-03 11:20', 'Correo electrónico': 'familia27@example.com',
    'Nombre y apellidos del alumno/a': 'Julia Navas Osma', 'Curso': '4º Enseñanzas Profesionales',
    'Especialidad': 'Canto', 'Edad': '19', 'Teléfono': '600000027', 'Profesor/a tutor/a': 'L. Baena',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '18:00-18:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 26, 'Hora de inicio': '2025-09-03 12:00', 'Correo electrónico': 'familia28@example.com',
    'Nombre y apellidos del alumno/a': 'Enzo Palau Mir', 'Curso': '1º Enseñanzas Elementales',
    'Especialidad': 'Guitarra', 'Edad': '8', 'Teléfono': '600000028', 'Profesor/a tutor/a': 'S. Robles',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '17:00-17:30', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 27, 'Hora de inicio': '2025-09-03 12:30', 'Correo electrónico': 'familia06@example.com',
    'Nombre y apellidos del alumno/a': 'Nicolás Ferrer Alba', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Tuba', 'Edad': '13', 'Teléfono': '600000006', 'Profesor/a tutor/a': 'A. Redondo',
    'Localidad de residencia': 'Poblete', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'Sí',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '17:00-17:30', 'Observaciones': '' },
  { 'Id': 28, 'Hora de inicio': '2025-09-03 13:10', 'Correo electrónico': 'familia30@example.com',
    'Nombre y apellidos del alumno/a': 'Adrián Belda Ruz', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Percusión', 'Edad': '12', 'Teléfono': '600000030', 'Profesor/a tutor/a': 'J. Peña',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 29, 'Hora de inicio': '2025-09-03 13:45', 'Correo electrónico': 'familia31@example.com',
    'Nombre y apellidos del alumno/a': 'Sofía Baeza Antúnez', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Percusión', 'Edad': '13', 'Teléfono': '600000031', 'Profesor/a tutor/a': 'J. Peña',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 30, 'Hora de inicio': '2025-09-03 14:02', 'Correo electrónico': 'familia32@example.com',
    'Nombre y apellidos del alumno/a': 'Diego Lara Cepeda', 'Curso': '2º Enseñanzas Elementales',
    'Especialidad': 'Piano', 'Edad': '9', 'Teléfono': '600000032', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '', 'Miércoles': '', 'Jueves': '', 'Viernes': '16:00-16:30', 'Observaciones': '' },
  { 'Id': 31, 'Hora de inicio': '2025-09-03 14:30', 'Correo electrónico': 'familia03@example.com',
    'Nombre y apellidos del alumno/a': 'Óscar Miranda Vela', 'Curso': '1º Enseñanzas Profesionales',
    'Especialidad': 'Trompeta', 'Edad': '12', 'Teléfono': '600000008', 'Profesor/a tutor/a': 'A. Redondo',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'No', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '19:00-19:30', 'Miércoles': '', 'Jueves': '19:00-19:30', 'Viernes': '', 'Observaciones': '' },
  { 'Id': 32, 'Hora de inicio': '2025-09-03 15:00', 'Correo electrónico': 'familia11@example.com',
    'Nombre y apellidos del alumno/a': 'Vega Solís Prado', 'Curso': '3º Enseñanzas Profesionales',
    'Especialidad': 'Piano', 'Edad': '15', 'Teléfono': '600000007', 'Profesor/a tutor/a': 'M. Ortega',
    'Localidad de residencia': 'Ciudad Real', '¿Solicita cabina con piano?': 'Sí', '¿Es para un hueco entre clases?': 'No',
    'Lunes': '', 'Martes': '18:00-18:30', 'Miércoles': '', 'Jueves': '', 'Viernes': '', 'Observaciones': '' }
];
